services:
  postgres:
    image: postgres:17
    container_name: postgres-db
    restart: always
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - db-net
      - local-net

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pga.rule=Host(`pga.localhost`)"
      - "traefik.http.routers.pga.entrypoints=web"
      - "traefik.http.services.pga.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy-net"
    ports:
      - "${PGADMIN_PORT}:80"
    expose:
      - "80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - db-net
      - proxy-net
      - local-net

volumes:
  postgres_data:
    external: true
  pgadmin_data:
    external: true

networks:
  db-net:
    external: true
  proxy-net:
    external: true
  local-net:
    driver: bridge