FROM php:8.2-apache

LABEL maintainer="hadiadriansyah21@gmail.com"
LABEL description="Base Docker image for web development with PHP 8.2 and Apache, including Composer"

ARG DOC_ROOT=/var/www/html
ENV APACHE_DOCUMENT_ROOT=${DOC_ROOT}

RUN apt-get update && apt-get install -y \
    git unzip zip curl \
    libpng-dev libjpeg-dev libfreetype6-dev libonig-dev libzip-dev libpq-dev \
    && docker-php-ext-install \
        pdo \
        pdo_mysql \
        mysqli \
        mbstring \
        zip \
        gd \
        pdo_pgsql \
        pgsql \
    && docker-php-ext-enable pdo_mysql pdo_pgsql

RUN a2enmod rewrite

RUN sed -i "s|DocumentRoot /var/www/html|DocumentRoot ${APACHE_DOCUMENT_ROOT}|g" /etc/apache2/sites-available/000-default.conf \
 && sed -i "/<Directory \/var\/www\/>/,/<\/Directory>/ s|AllowOverride None|AllowOverride All|" /etc/apache2/apache2.conf

WORKDIR /var/www/html

# COPY projects/project_name/src/ /var/www/html/ # Uncomment this line to copy your project files into the container

COPY --from=composer:2.7 /usr/bin/composer /usr/bin/composer

RUN chown -R www-data:www-data /var/www/html
# RUN chown -R www-data:www-data /var/www/html && chmod -R 755 /var/www/html/storage /var/www/html/bootstrap/cache

EXPOSE 80

CMD ["apache2-foreground"]