FROM php:8.3-apache

LABEL maintainer="hadiadriansyah21@gmail.com"
LABEL description="Base Docker image for web development with PHP 8.3 and Apache, including Composer"

# # Uncomment this section if you are not using a custom Apache configuration file.
# # These lines set the default document root for Apache inside the container.
# ARG DOC_ROOT=/var/www/html
# ENV APACHE_DOCUMENT_ROOT=${DOC_ROOT}

RUN apt-get update && apt-get install -y \
    git unzip zip curl \
    libpng-dev libjpeg-dev libfreetype6-dev libonig-dev libzip-dev libpq-dev \
    && docker-php-ext-install \
        pdo \
        pdo_mysql \
        mysqli \
        mbstring \
        zip \
        gd \
        pdo_pgsql \
        pgsql \
    && docker-php-ext-enable pdo_mysql pdo_pgsql

RUN a2enmod rewrite


# Uncomment the following lines to change the Apache DocumentRoot and enable .htaccess overrides.
# RUN sed -i "s|DocumentRoot /var/www/html|DocumentRoot ${APACHE_DOCUMENT_ROOT}|g" /etc/apache2/sites-available/000-default.conf \
#  && sed -i "/<Directory \/var\/www\/>/,/<\/Directory>/ s|AllowOverride None|AllowOverride All|" /etc/apache2/apache2.conf

# Uncomment the following line to use a custom Apache virtual host configuration.
COPY ../../apache/custom.localhost.conf /etc/apache2/sites-available/custom.localhost.conf

WORKDIR /var/www/html

# COPY projects/project_name/src/ /var/www/html/ # Uncomment this line to copy your project files into the container

COPY --from=composer:2.8 /usr/bin/composer /usr/bin/composer

RUN chown -R www-data:www-data /var/www/html
# RUN chown -R www-data:www-data /var/www/html && chmod -R 755 /var/www/html/storage /var/www/html/bootstrap/cache

EXPOSE 80

CMD ["apache2-foreground"]