services:
  mysql:
    image: mysql:8.4.5
    container_name: mysql-db
    restart: always
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      # MYSQL_DATABASE: ${MYSQL_DATABASE}
      # MYSQL_USER: ${MYSQL_USER}
      # MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - db-net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: ${PMA_HOST}
      PMA_PORT: ${PMA_PORT}
      UPLOAD_LIMIT: ${UPLOAD_LIMIT}
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.http.routers.pma.rule=Host(`pma.localhost`)"
    #   - "traefik.http.routers.pma.entrypoints=web"
    #   - "traefik.http.services.pma.loadbalancer.server.port=80"
    #   - "traefik.docker.network=proxy-net"
    # ports:
    #   - "${PMA_GUI_PORT}:80"
    # expose:
    #   - "80"
    depends_on:
      - mysql
    networks:
      - db-net
      - proxy-net
      - local-net

volumes:
  mysql_data:
    external: true

networks:
  db-net:
    external: true
  proxy-net:
    external: true
  local-net:
    driver: bridge