services:
  mysql5:
    image: mysql:5.7
    container_name: mysql5-db
    restart: always
    ports:
      - "${MYSQL5_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      # MYSQL_DATABASE: ${MYSQL_DATABASE}
      # MYSQL_USER: ${MYSQL_USER}
      # MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql5_data:/var/lib/mysql
    networks:
      - db-net

  phpmyadmin5:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin5
    restart: always
    environment:
      PMA_HOST: ${PMA5_HOST}
      PMA_PORT: ${PMA_PORT}
      UPLOAD_LIMIT: ${UPLOAD_LIMIT}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pma5.rule=Host(`pma5.localhost`)"
      - "traefik.http.routers.pma5.entrypoints=web"
      - "traefik.http.services.pma5.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy-net"
    ports:
      - "${PMA5_GUI_PORT}:80"
    expose:
      - "80"
    depends_on:
      - mysql5
    networks:
      - db-net
      - proxy-net

volumes:
  mysql5_data:
    external: true

networks:
  db-net:
    external: true
  proxy-net:
    external: true