services: 
  mongo:
    image: mongo:8.0.9
    container_name: mongo-db
    restart: always
    ports:
      - "${MONGO_PORT}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASS}
    volumes:
      - mongo_data:/data/db
    networks:
      - db-net

volumes:
  mongo_data:
    external: true

networks:
  db-net:
    external: true