services:
  traefik:
    image: traefik:v3.4.0
    container_name: traefik
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - ./dynamic_conf.yml:/etc/traefik/dynamic_conf.yml:ro
      - ./acme.json:/etc/traefik/acme.json
    networks:
      - proxy-net

networks:
  proxy-net:
    external: true