services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "81:80"
    volumes:
      - ./conf.d:/etc/nginx/conf.d:ro
    networks:
      - proxy-net

networks:
  proxy-net:
    external: true