services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "81:80"
    env_file:
      - .env
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf.d:/etc/nginx/conf.d:ro
      - ../../projects/laravel/src:/var/www/html/laravel
    networks:
      - proxy-net

networks:
  proxy-net:
    external: true