services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "81:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf.d:/etc/nginx/conf.d:ro
      - /var/www/Apps/docker-environment/proxy/nginx/sites-available:/var/www/Apps/docker-environment/proxy/nginx/sites-available:ro
      - /var/www/Apps/docker-environment/projects:/var/www/html:ro
    networks:
      - proxy-net

networks:
  proxy-net:
    external: true